### ISSUE TITLE
Install error (tensorflow-gpu)

### ISSUE THREAD

**Issue by akatav** [ari-dasci/S-TSFE-DL#2]
Hi,
I ge the following error on doing pip3 install tsfedl

Collecting tensorflow-gpu (from tsfedl)
  Downloading tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

Could you please update your installation instructions accordingly ?

**Comment by nacheteam** [comment]
Installation has been updated in the newest version.
